server:
  port: 8081
  servlet:
    context-path: /spring-boot
spring:
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true
  profiles:
    include: demo
  banner:
    charset: utf-8
